### ISSUE TITLE
Bakelet for NodeJS not installing

### ISSUE THREAD

**Issue by Shh25** [ottomatica/Baker#101]
**Error Description**
Getting the error:
Error: Error: Cannot find module '/snapshot/Baker/lib/bakelets/tools/nodejs

**To Reproduce**
1. baker.yml file:

```
name: xyz
vm:
  ip: <ip_address>
tools:
  - nodejs9
```

2. Run `baker bake`

**Expected behavior**
It should have installed nodeJS as a tool on the given VM.

**Screenshots**
<img width="517" alt="screen shot 2019-02-14 at 7 40 45 pm" src="https://user-images.githubusercontent.com/13828906/52826927-badd4d00-3090-11e9-8fcb-611ebc0f2970.png">

**Please complete the following information:**
 - OS: MacOS
 - Version 10.14

**Comment by Shh25** [comment]
Need to use lang instead of tool.

**Comment by chrisparnin** [comment]
In looks like you're using `tools`, when it is expecting `lang`. Sounds like we can use a better error message here.

```yaml
name: suites
vm:
  ip: 192.168.33.50
lang:
  - nodejs9
```

You can also verify all the bakelets names by checking here:
https://github.com/ottomatica/bakelets-source
