### ISSUE TITLE
Support VirtualBox 6.0 

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/Baker#119]
Baker fails to work with virtualbox 6.0. Downgrading to 5.xx works as expected.

Need to investigate why and update https://github.com/ottomatica/node-virtualbox

**Comment by gjabell** [comment]
See if [https://github.com/ottomatica/node-virtualbox/pull/27](https://github.com/ottomatica/node-virtualbox/pull/27) works for you! Still needs some work with tests I think, and maybe a better way to deal with v5 vs v6 but it's a start.

**Comment by chrisparnin** [comment]
Merged node-virtualbox fix and bumped up version: https://github.com/ottomatica/Baker/commit/d2351b4abfee8ec858b17bebb85a62985ca22884

Should be fixed!
