### ISSUE TITLE
Missing package.json?

### ISSUE THREAD

**Issue by monkeysuffrage** [ottomatica/Baker#51]
**Describe the bug**
`npm link` fails because of missing package.json

**Comment by chrisparnin** [comment]
Ok. You might need to make sure you're in the `src` directory first. Sorry if that wasn't clear.

**Comment by monkeysuffrage** [comment]
Oh, there is is. You might consider making that top level, otherwise updating the "install from source" instruction.

**Comment by chrisparnin** [comment]
Yep. This prompted us to go ahead and move things into the top-level directory. Thanks for the suggestion.
