### ISSUE TITLE
cluster.js and interactive.js have invalid import references

### ISSUE THREAD

**Issue by gjabell** [ottomatica/Baker#90]
**Describe the bug**
After installing baker from source, the `baker` command fails because it cannot locate `Spinner.js` in `cluster.js` and `interactive.js`.

**To Reproduce**
1. Clone the baker repo and switch to dev branch.
2. Run `npm install` and `npm link`.
3. Attempt to run the `baker` command.

**Expected behavior**
The baker command runs successfully without failing from import errors.

**Please complete the following information:**
- OS: Arch Linux 64-bit
- Version: Kernel 4.20.0

**Comment by ssmirr** [comment]
Thanks for reporting and sending a PR to fix this Galen!

Interesting/weird thing is that node on Mac and Windows didn't complain about using `../Spinner` instead of `./spinner`. Wondering if node checks imports differently on each OS 🤔 .

**Comment by gjabell** [comment]
I think Linux has stricter rules when it comes to case-sensitivity. I've even had issues with database tables not being recognized if they are capitalized vs. lowercase, so I wouldn't be surprised if node is the same way.
